spring:
  datasource:
    hikari:
      max-lifetime: 180000
      keepalive-time: 60000
      connection-timeout: 30000
    # Render External URL ko JDBC format mein convert kiya gaya hai
    url: jdbc:postgresql://dpg-d5e3k20gjchc739gg8jg-a.oregon-postgres.render.com/whatsappdb_f45k
    username: whatsappdb_f45k_user
    password: Iygnr6qHzocbCkRTuTEnhIsQFY10oBF2
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:RSM_WHATSAPP_SUPER_SECRET_KEY_1234567890}
  expiration: 86400000

app:
  # Ye tabhi chalega jab aapne FirebaseConfig update kiya ho
  firebase-config-file: classpath:firebase-service-account.json