spring:
  application:
    name: rsmwhatsapp

  # Database Configuration (In-Memory H2 Database)
  datasource:
    url: jdbc:h2:mem:whatsappdb
    driverClassName: org.h2.Driver
    username: sa
    password:

  # H2 Console (Aap browser mein database dekh payenge)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA / Hibernate settings
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true # Taaki aap console mein queries dekh saken

# Server Port
server:
  port: 8080