spring:
  datasource:
    hikari:
      max-lifetime: 180000 # 3 minutes (Render ke liye sahi hai)
      keepalive-time: 60000 # 1 minute
      connection-timeout: 30000
    # 'jdbc:' prefix zaroori hai
    url: jdbc:postgresql://dpg-d5e3k20gjchc739gg8jg-a.oregon-postgres.render.com/whatsappdb_f45k
    username: whatsappdb_f45k_user
    password: Iygnr6qHzocbCkRTuTEnhIsQFY10oBF2
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # Dialect hatane se warning band ho jayegi

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:RSM_WHATSAPP_SUPER_SECRET_KEY_1234567890} # Default value ke saath
  expiration: 86400000

app:
  firebase-config-file: classpath:firebase-service-account.json