spring:
  # 1. PostgreSQL Configuration
  datasource:
    url: postgresql://whatsappdb_f45k_user:Iygnr6qHzocbCkRTuTEnhIsQFY10oBF2@dpg-d5e3k20gjchc739gg8jg-a.oregon-postgres.render.com/whatsappdb_f45k
    username: whatsappdb_f45k_user
    password: Iygnr6qHzocbCkRTuTEnhIsQFY10oBF2 # Apna password yahan likhein
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 2. File Upload Settings (Images & Documents)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 3. JWT Security Constants
jwt:
  secret: RSM_WHATSAPP_SUPER_SECRET_KEY_1234567890 # Isse lamba aur secret rakhein
  expiration: 86400000 # 1 din (milliseconds mein)

# 4. Firebase Configuration (Push Notifications)
app:
  firebase-config-file: classpath:firebase-service-account.json