spring:
  # 1. PostgreSQL Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/whatsappdb
    username: postgres
    password: 1234 # Apna password yahan likhein
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 2. File Upload Settings (Images & Documents)
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# 3. JWT Security Constants
jwt:
  secret: RSM_WHATSAPP_SUPER_SECRET_KEY_1234567890 # Isse lamba aur secret rakhein
  expiration: 86400000 # 1 din (milliseconds mein)

# 4. Firebase Configuration (Push Notifications)
app:
  firebase-config-file: classpath:firebase-service-account.json